# Generated by Django 4.2.4 on 2023-08-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fband', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(default='C:/Users/Sidwe/OneDrive/Documents/HyperionDev/Level 2/L2T23/myBand/static/images', upload_to='album_covers/'),
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
